### ISSUE TITLE
"as_quant.py error"

### ISSUE THREAD

**Issue by oknsvm** [compbiolabucf/AS-Quant#6]
Hi, 
I wanted to use AS-Quant for checking how splicing is affected. But the code gives me this kind of error! Until this point, everything was looking fine! I have 3 replicates in each folder! What was the reason for the error? Many thanks in advance... 

The code and the output: 
python3 as_quant.py -s hg38 -i ../kg1_chir/ ../kg1_dmso/ -o try -method ranksum
###
Running AS-Quant for detecting significant annotated splicing events...
Spliced Exon type:  SE
Executing:  kg1_chir in group 1
Starting: chr1
Traceback (most recent call last):
  File "/mnt/d/MyProjects/RIP-AlternativeSplicing-2023-01-02/AS-Quant/as_quant.py", line 106, in <module>    methods.Find_splicing_events(ChromDict_merged, chromosomes, AS, input1_dir, species, sample, output_dir)
  File "/mnt/d/MyProjects/RIP-AlternativeSplicing-2023-01-02/AS-Quant/methods.py", line 154, in Find_splicing_events
    bam_df = pd.read_csv(os.path.join(input_dir, sample, chrom+".txt"), delimiter='\t')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/okansevim/miniconda3/envs/AS-Quant/lib/python3.11/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../kg1_chir/kg1_chir/chr1.txt'
###
Best regards,
Okan

**Comment by naimafahmi** [comment]
Did you try the test data? did they work fine?

**Comment by oknsvm** [comment]
Hi,

I did try with the sample data. They did not work, either.
